### ISSUE TITLE
[BUG]The download action cannot be recorded in 1.12.1.

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#498]
Today I upgraded to the latest version. (1.11. 0 - > 1.12. 1) , I find that all test case scripts involving waitForDownload report error timeout. (You can see that the file has been downloaded, but the waitForDownload method is executed until timeout.) I tried to record the download with Inspector, but there was no response when I clicked the download button, only page.click("selector") was recorded.

**Comment by yury-s** [comment]
Can you share your test case? All our download tests pass on that version.

**Comment by LongLiveY96** [comment]
Just a simple operation. Click the Export button,`Download download = page.waitForDownload(() -> page.click("text=export"));`(The code is generated based on version 1.11.0, and run in 1.12.1) When my test case script reaches this step, it times out.And throws Error
```
com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded

	at com.microsoft.playwright.impl.WaitableTimeout.get(WaitableTimeout.java:41)
	at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:44)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.PageImpl.waitForEventWithTimeout(PageImpl.java:529)
	at com.microsoft.playwright.impl.PageImpl.waitForDownloadImpl(PageImpl.java:472)
	at com.microsoft.playwright.impl.PageImpl.lambda$waitForDownload$2(PageImpl.java:465)
	at com.microsoft.playwright.impl.WaitForEventLogger.get(WaitForEventLogger.java:46)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withWaitLogging(ChannelOwner.java:72)
	at com.microsoft.playwright.impl.PageImpl.waitForDownload(PageImpl.java:465)
	at com.microsoft.playwright.Page.waitForDownload(Page.java:4151)

```
I added `page.pause()` before doing this. You can see that the file has been successfully downloaded but is waiting for the download to complete.
![image](https://user-images.githubusercontent.com/23394317/122522317-683d4280-d048-11eb-9d74-6de6a45fd915.png)
![image](https://user-images.githubusercontent.com/23394317/122522329-6d9a8d00-d048-11eb-855f-6758bd839e17.png)
![image](https://user-images.githubusercontent.com/23394317/122522281-5a87bd00-d048-11eb-8e00-f1940f73eac3.png)
I switch version to 1.11.1, run the same script,and result is ok.
![image](https://user-images.githubusercontent.com/23394317/122522859-fca7a500-d048-11eb-9555-609270eb3501.png)

**Comment by LongLiveY96** [comment]
btw, When I click Record and click Export button, the code cyclically displays page.click ("Export button"), but the page does not trigger the download event.
![image](https://user-images.githubusercontent.com/23394317/122524176-6c6a5f80-d04a-11eb-850e-83e87120323c.png)

**Comment by LongLiveY96** [comment]
When I switched chromeium from 90.0.4430.0 to 93.0.4530.0, the problem was solved.So this is because the new version of playwright is incompatible with the old version of chromeium, right? Anyway, thank you for your answer.

**Comment by yury-s** [comment]
> When I switched chromeium from 90.0.4430.0 to 93.0.4530.0, the problem was solved.

Good finding! May I ask you why you need to use custom Chromium installation (I assume you configure it via [`setExecutablePath`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch))? With the recently added channel support it is possible to test with Chrome/Edge stable/beta, I'm curious why it doesn't work for you?

> So this is because the new version of playwright is incompatible with the old version of chromeium, right? Anyway, thank you for your answer.

Correct. The problem is that with https://github.com/microsoft/playwright/pull/6082 we changed how downloads are handled internally and that change requires Chromium version  91+ because it uses a new API in the browser. Basically most of the features will work with the older browsers but some of them like downloads in this case may fail. Each playwright release is test with current Chrome stable version (can be found in the release notes) and that version could be considered the minimal required Chromium version if you want all features to work correctly.

**Comment by LongLiveY96** [comment]
> 
> Good finding! May I ask you why you need to use custom Chromium installation (I assume you configure it via [`setExecutablePath`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch))? With the recently added channel support it is possible to test with Chrome/Edge stable/beta, I'm curious why it doesn't work for you?
> 


The company network does not connect to microsoft's cdn, so downloading the corresponding browser of playwright via mvn exec is cumbersome, especially on linux. So I update the browser version every once in a while. It would be nice if there was a way to get the latest Playwright browser online (such as downloading it on the web).

**Comment by LongLiveY96** [comment]
> > The company network does not connect to microsoft's cdn, so downloading the corresponding browser of playwright via mvn exec is cumbersome, especially on linux. So I update the browser version every once in a while.
> 
> You have likely seen [this page](https://github.com/microsoft/playwright/blob/af060938699aad5c8e7695016258bb8c0a242764/src/utils/registry.ts#L354) that describes some ways to install behind a firewall. If you can download the browser manually in a browser from the same machine it should be possible to configure Playwright installer to achieve the same. Or do you download on a different machine that has access to the CDN and then copy the source over the local network?
> 
> > It would be nice if there was a way to get the latest Playwright browser online (such as downloading it on the web).
> 
> There is no such way because the latest one would most of the time correspond to the next unreleased version while most people would need current stable. With that said all browsers can be downloaded via web links like https://playwright.azureedge.net/builds/chromium/891964/chromium-linux.zip, see [this registry](https://github.com/microsoft/playwright/blob/af060938699aad5c8e7695016258bb8c0a242764/src/utils/registry.ts#L354). You'd need to know right browser version though (the one in [browsers.json](https://github.com/microsoft/playwright/blob/master/browsers.json)).
> 

It's useful. I can use the address you provided at the end to download on my own computer and transfer to the required machine. Thanks again！😄

**Comment by SilenceCarrot** [comment]
Hello, I would like to ask a question about downloading.

My browser is up to date, but the download problem persists. I've run out of ideas to solve this, and I really hope to get your help.
my question is here：https://github.com/microsoft/playwright-java/issues/935
